---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 'stretch'

inputs:
  - name: source-code

outputs:
  - name: build-output

run:
  path: source-code/ci/build.sh